-- 코드를 입력하세요
SELECT I.NAME, I.DATETIME
FROM ANIMAL_INS I
WHERE NOT EXISTS (
                SELECT O.NAME 
                FROM ANIMAL_OUTS O
                WHERE I.ANIMAL_ID = O.ANIMAL_ID
)
ORDER BY I.DATETIME
LIMIT 3